no_index: 
  directory: 
    - inc
    - t
generated_by: hand
distribution_type: module
version: 0.20
name: Jemplate
author: "Ingy d\xC3\xB6t Net <ingy@cpan.org>"
license: perl
requires: 
  perl: 5.6.1
  Template: 2.14
  File::Find::Rule: 0.30
abstract: JavaScript Templating with Template Toolkit
