--- 
abstract: JavaScript Templating with Template Toolkit
author: "Ingy d\xC3\xB6t Net <ingy@cpan.org>"
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Jemplate
no_index: 
  directory: 
    - examples
    - inc
    - t
requires: 
  File::Find::Rule: 0.30
  Template: 2.14
  perl: 5.6.1
version: 0.21
