---
abstract: 'JavaScript Templating with Template Toolkit'
author:
  - 'Ingy döt Net <ingy@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.87'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Jemplate
no_index:
  directory:
    - examples
    - inc
    - t
requires:
  File::Find::Rule: 0.30
  Template: 2.19
  perl: 5.6.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.23_1
