---
abstract: 'JavaScript Templating with Template Toolkit'
author:
  - 'Ingy döt Net <ingy@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Jemplate
name: Jemplate
no_index:
  directory:
    - examples
    - inc
    - t
requires:
  File::Find::Rule: 0.30
  Filter::Util::Call: 0
  Template: 2.14
  perl: 5.6.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.262
